export const LOCATION_START = "LOCATION_START";
export const LOCATION_END = "LOCATION_END";
export const LOCATION_SUCCESS = "LOCATION_SUCCESS";
export const LOCATION_FAIL = "LOCATION_FAIL";

export const SAVE_LOCATION_SUCCESS = "SAVE_LOCATION_SUCCESS";
